#!/usr/bin/env node
// Bring the whole local backend up, on a 5.9 GB machine, in one command.
//
//   node scripts/backend-up.mjs
//
// Steps: start Supabase (trimmed) -> read its keys -> write apps/web/.env.local
// -> apply migrations -> create the platform admin.
//
// WHY THE TRIM: a default `supabase start` boots ~10 containers. Studio,
// Logflare, Vector, imgproxy, Mailpit and Supavisor are developer conveniences
// this app never calls — but Logflare in particular is a memory hog, and this
// machine has 5.9 GB total with Windows already holding ~2.5 GB. Excluding them
// leaves exactly what Parisar uses: Postgres, Auth, PostgREST, Realtime,
// Storage and the Edge Runtime.
//
// Safe to re-run. `supabase start` is idempotent, and so is the admin script.

import { execSync, spawnSync } from "node:child_process";
import { existsSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const ENV_PATH = resolve(ROOT, "apps/web/.env.local");

// Containers Parisar never talks to. Dropped to fit a small machine.
const EXCLUDE = [
  "studio",
  "logflare",
  "vector",
  "imgproxy",
  "mailpit",
  "supavisor",
  "postgres-meta",
].join(",");

const step = (n, msg) => console.log(`\n[${n}] ${msg}`);
const die = (msg) => {
  console.error(`\n✗ ${msg}`);
  process.exit(1);
};

// --- 0. prerequisites --------------------------------------------------------
step(0, "Checking prerequisites…");
for (const [cmd, hint] of [
  ["docker --version", "Docker Desktop is not installed — run INSTALL-PARISAR-BACKEND.bat on your Desktop."],
  ["supabase --version", "Supabase CLI is not installed — run INSTALL-PARISAR-BACKEND.bat on your Desktop."],
]) {
  try {
    execSync(cmd, { stdio: "pipe" });
  } catch {
    die(hint);
  }
}
try {
  execSync("docker info", { stdio: "pipe" });
} catch {
  die("Docker is installed but not running. Open Docker Desktop, accept its terms, wait for the whale to go green, then re-run this.");
}
console.log("    docker ✓  supabase ✓");

// --- 1. start ----------------------------------------------------------------
step(1, `Starting Supabase (excluding: ${EXCLUDE})…`);
const start = spawnSync("supabase", ["start", "-x", EXCLUDE], {
  cwd: ROOT,
  stdio: "inherit",
  shell: true,
});
if (start.status !== 0) die("`supabase start` failed. Check the output above.");

// --- 2. keys -----------------------------------------------------------------
step(2, "Reading keys from `supabase status`…");
let status = "";
try {
  status = execSync("supabase status -o env", { cwd: ROOT, encoding: "utf8", shell: true });
} catch {
  die("`supabase status` failed.");
}
const pick = (k) => (status.match(new RegExp(`^${k}="?([^"\\r\\n]+)"?`, "m")) || [])[1];
const apiUrl = pick("API_URL") || "http://127.0.0.1:54321";
const anon = pick("ANON_KEY");
const service = pick("SERVICE_ROLE_KEY");
const dbUrl = pick("DB_URL") || "postgresql://postgres:postgres@127.0.0.1:54322/postgres";
if (!anon || !service) die("Could not parse ANON_KEY / SERVICE_ROLE_KEY out of `supabase status`.");

// --- 3. env ------------------------------------------------------------------
step(3, `Writing ${ENV_PATH}…`);
writeFileSync(
  ENV_PATH,
  `# Generated by scripts/backend-up.mjs — real keys from the running local stack.
NEXT_PUBLIC_SUPABASE_URL=${apiUrl}
NEXT_PUBLIC_SUPABASE_ANON_KEY=${anon}
SUPABASE_SERVICE_ROLE_KEY=${service}

OTP_PROVIDER=stub
SUPABASE_DB_URL=${dbUrl}
`,
  "utf8",
);
console.log("    keys written ✓");

// --- 4. migrations -----------------------------------------------------------
step(4, "Applying migrations (43 files) + seed…");
const reset = spawnSync("supabase", ["db", "reset"], { cwd: ROOT, stdio: "inherit", shell: true });
if (reset.status !== 0) die("`supabase db reset` failed — the schema did not apply.");

// --- 5. admin ----------------------------------------------------------------
step(5, "Creating the platform admin…");
const admin = spawnSync(process.execPath, [resolve(ROOT, "scripts/create-admin.mjs")], {
  cwd: ROOT,
  stdio: "inherit",
});
if (admin.status !== 0) die("Admin creation failed.");

console.log(`
============================================================
 BACKEND UP.

   Web app     http://localhost:3000     (pnpm --filter @parisar/web dev)
   Supabase    ${apiUrl}

   Admin login  phone 9000000001   OTP 123456   -> /admin
============================================================
`);
if (!existsSync(ENV_PATH)) die("env file missing — unexpected.");
